name: tests
on:
  pull_request:
  push:
    branches: [ main ]

  schedule:
  - cron: '25 09 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

defaults:
  run:
    shell: bash

# This is required for "gautamkrishnar/keepalive-workflow"
permissions:
  contents: write

env:
  # Allow ddev get to use a GitHub token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
    - uses: ddev/github-action-add-on-test@v1
      with:
        ddev_version: "stable"
        token: ${{ secrets.GITHUB_TOKEN }}
        addon_repository: ${{ env.GITHUB_REPOSITORY }}
        addon_ref: ${{ env.GITHUB_REF }}
